import z from "zod";


export const BASE_EXCEPTION_CODE = {
    ARGUMENT_INVALID: 'ARGUMENT_INVALID',
    ARGUMENT_NOT_PROVIDED: 'ARGUMENT_NOT_PROVIDED',
    ARGUMENT_OUT_OF_RANGE: 'ARGUMENT_OUT_OF_RANGE',
    CONFLICT: 'CONFLICT',
    NOT_FOUND: 'NOT_FOUND',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
    INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    EXPIRED_TOKEN: 'AUTH_EXPIRED',
    FORBIDDEN: 'FORBIDDEN',
} as const;
export const BaseExceptionCode = z.enum(BASE_EXCEPTION_CODE);
export type BaseExceptionCode = z.infer<typeof BaseExceptionCode>;