name: Feature
description: 새로운 기능을 요청하는 템플릿입니다.
title: "[Feature]: "
labels:
  - feature
body:
  - type: input
    id: summary
    attributes:
      label: 기능 요약
      description: 구현하려는 기능을 간단히 작성해주세요.
      placeholder: 로그인 기능 추가
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 상세 설명
      description: 기능이 필요한 이유와 세부 내용을 작성해주세요.
      placeholder: |
        - 사용자 인증을 위해 필요합니다.
        - 로그인 실패 시 오류 메시지 노출 필요.
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 작업 항목
      description: 수행해야 할 작업을 체크박스 리스트로 나열해주세요.
      placeholder: |
        - [ ] API 엔드포인트 생성
        - [ ] UI 개발
        - [ ] Validation 처리
    validations:
      required: false

  - type: input
    id: reference
    attributes:
      label: 참고 자료
      description: 관련 문서나 링크가 있다면 추가해주세요.
    validations:
      required: false
